name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      sha_tag: ${{ steps.meta.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/jyf0214/qinglong
          tags: |
            type=sha,prefix=,format=short,key=version
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          no-cache: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  preview-deployment:
    runs-on: ubuntu-latest
    needs: build_and_push
    if: github.event_name == 'push'
    steps:
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download and install cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

      - name: Run Docker container
        run: |
          docker run -d --name qinglong-app -p 5700:5700 ghcr.io/jyf0214/qinglong:${{ needs.build_and_push.outputs.sha_tag }}

      - name: Check container status
        run: |
          sleep 20
          docker ps -a
          docker logs qinglong-app

      - name: Run cloudflared tunnel
        run: |
          cloudflared tunnel --url http://localhost:5700 > cloudflared.log 2>&1 &
          sleep 10
          cat cloudflared.log

      - name: Wait for 5 minutes
        run: sleep 300

      - name: Stop container and tunnel
        run: |
          docker stop qinglong-app
          killall cloudflared